name: itunda
description: "A modern community marketplace and food delivery app connecting neighborhoods."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# Alternatively, dependencies can be manually updated by changing the version numbers below.
# Then run `flutter pub get` to install the new versions.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # UI and styling
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  
  # State management
  provider: ^6.1.1
  flutter_riverpod: ^2.3.6
  
  # Networking and data handling
  http: ^1.3.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image handling and caching
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  
  # Navigation
  go_router: ^10.1.2
  
  # Authentication
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  
  # Utilities
  url_launcher: ^6.1.14
  intl: ^0.19.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.2
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  
  # Performance optimization
  flutter_displaymode: ^0.6.0
  flutter_cache_manager: ^3.3.1
  flutter_lazy_indexed_stack: ^0.0.5
  diffutil_dart: ^4.0.0
  tuple: ^2.0.2
  
  # Error tracking
  sentry_flutter: ^7.10.1
  flutter_secure_storage: ^9.2.4
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  photo_view: ^0.15.0
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.3
  stomp_dart_client: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  mockito: ^5.4.2
  # Using a compatible code analysis package
  custom_lint: ^0.5.8

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4286F5" # Itunda blue
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#4286F5"
    theme_color: "#4286F5"

# Flutter native splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#17181D"
  image: assets/images/splash_logo.png
  image_dark: assets/images/splash_logo.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#17181D"
    image: assets/images/splash_logo.png
    image_dark: assets/images/splash_logo.png
    icon_background_color: "#4286F5"
    icon_background_color_dark: "#4286F5"
  android: true
  ios: true
  web: true

# Automatically resizing assets for different screen sizes
flutter_screenutil:
  designSize:
    width: 375
    height: 812

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
